name: Update README with Language Chart

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs at midnight UTC every day

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Generate Mermaid Chart
      run: python generate_mermaid_chart.py > mermaid_chart.md
    - name: Update README
      run: |
        sed -i '/<!-- mermaid-chart-start -->/,/<!-- mermaid-chart-end -->/c\<!-- mermaid-chart-start -->\n$(cat mermaid_chart.md)\n<!-- mermaid-chart-end -->' README.md
    - name: Commit and Push
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add README.md
        git commit -m 'Update README with language chart' || echo "No changes to commit"
        git push
