name: Update README with Mermaid Chart

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install matplotlib
      - name: Generate Pie Chart and Update README
        run: |
          python update_readme_with_chart.py
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md language_pie_chart.png
          git commit -m 'Automatically update README with pie chart' || echo "No changes to commit"
          git push
